[theme]
primaryColor = "#667eea"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[server]
port = 8502
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
